version: "3.9"

services:

  postgres:
    image: "postgres:13.4-alpine"
    restart: always
    environment:
      - POSTGRES_USER=hexagonal
      - POSTGRES_PASSWORD=hexagonal
      - POSTGRES_DB=hexagonal
    ports:
      - "6666:5432"

  wiremock-slack:
    image: wiremock/wiremock:latest
    volumes:
      - ./root/adapter-driven/thirdparty-http/src/test/resources/wiremock/__files/:/home/wiremock/__files/:z
      - ./root/adapter-driven/thirdparty-http/src/test/resources/wiremock/mappings/:/home/wiremock/mappings/:z
    command:
      - --verbose
      - --global-response-templating
    ports:
      - "9966:8080"
