version: "3.9"

services:

  postgres:
    image: "postgres:13.4-alpine"
    restart: always
    environment:
      - POSTGRES_USER=hexagonal
      - POSTGRES_PASSWORD=hexagonal
      - POSTGRES_DB=hexagonal
    ports:
      - "6666:5432"
